name: Build Next.js Project
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - test 
  pull_request:
    branches:
      - test 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js Project
        run: yarn nextbuild

      - name: Deploy to Vercel
        run: vercel deploy  --prod --token=${{ secrets.VERCEL_TOKEN }}

    

